blank_issues_enabled: false
contact_links:
  - name: WebUI developer repository
    url: https://github.com/hlky/stable-diffusion-webui/issues/new/choose
    about: MOST BUGS SHOULD GO HERE Have a bug related to the features? Please open a bug on the developer repository.
  - name: Feature Request, Question or Suggestion
    url: https://github.com/hlky/stable-diffusion-webui/discussions
    about: Please create a discussion and see if folks have already solved it
  - name: Colab version specific bug? 
    url: https://github.com/altryne/sd-webui-colab/issues/new/choose
    about: Please open colab related bugs here
